Break Unused Loop
qbcore-framework/qb-skillbar pull request #12
Opened 2022-09-05 00:03 UTC by KamuiKody

**Describe Pull request**
breaks the unused loop and calls it in a function

If your PR is to fix an issue mention that issue here

**Questions (please complete the following information):**
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? [yes/] (Be honest)
- Does your code fit the style guidelines? [yes/]
- Does your PR fit the contribution guidelines? [yes/]

2022-09-05 02:12 UTC, mrdiamonddirt approved these changes
checked, Works

2022-09-05 03:34 UTC, GhzGarage commented
Linting error

2022-09-05 16:09 UTC, tom-osborne commented
Rather than creating a new variable called `looped` I think you can make use of the .active attribute to achieve the same thing. It looks like you're just repeating that check with a new variable?

2022-09-06 15:46 UTC, D4isDAVID requested changes

2022-09-06 15:46 UTC, D4isDAVID commented on client/main.lua
> +            Wait(1)
```suggestion
                Wait(1)
```
Fix indentation

2022-09-06 15:46 UTC, D4isDAVID commented on client/main.lua
> +                end
```suggestion
            while Skillbar.Data.Active do
                if IsControlJustPressed(0, 38) then
                    SendNUIMessage({
                        action = "check",
                        data = Skillbar.Data.Data,
                    })
                end
```
Remove extra condition check and unused variable

2022-09-06 16:13 UTC, D4isDAVID approved these changes
LGTM, tested and works

2022-09-11 14:20 UTC, izolox commented
Works fine for me

2022-09-11 14:35 UTC, tom-osborne approved these changes

2022-09-11 14:35 UTC, merged